FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY services/orders/main.go .
RUN CGO_ENABLED=0 go build -o orders .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/orders .
EXPOSE 3002
CMD ["./orders"]