FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY services/users/main.go .
RUN CGO_ENABLED=0 go build -o users .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/users .
EXPOSE 3001
CMD ["./users"]